name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go test ./...
      
      - uses: googleapis/release-please-action@v4
        with:
          release-type: go